Homework6: Iterators, Generators
NikitaKuzminn/Python_course_2023 pull request #7
Opened 2023-10-25 14:13 UTC by NikitaKuzminn

Two tasks of the module have been completed

2023-10-25 17:42 UTC, AnastasiiaGor requested changes

2023-10-25 17:42 UTC, AnastasiiaGor commented on Homeworks/src/main/Homework6/homework1.py
> +if __name__ == '__main__':
expected output: 1 2 3 6 z h a b a 1 2 3 4 
actual output: 1 2 3 6 zhaba 1 2 3 4

2023-10-26 10:04 UTC, NikitaKuzminn commented on Homeworks/src/main/Homework6/homework1.py
> +if __name__ == '__main__':
fixed)
thank you!

2023-11-08 18:15 UTC, AnastasiiaGor approved these changes

2023-11-24 17:41 UTC, merged